- name: Copy Docker Compose file to remote machine
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: /home/ubuntu/<working-dir>   # Local path to your docker-compose.yml
        dest: /home/ubuntu/  # Destination on remote machine

    - name: Run Docker Compose
      ansible.builtin.command:
        cmd: docker-compose -f /home/ubuntu/<working-dir>/docker-compose.yaml up
